spring:
  application:
    name: api-collab-dev
  # base de donnee configuration
  datasource:
    url: jdbc:mysql://localhost:3306/collabdevDB
    username: root
    password: Root2025@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



