spring:
  application:
    name: api-collab-dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # base de donnee configuration
  datasource:
    url: jdbc:mysql://localhost:3306/collabdevDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


# Configuration pour le stockage des fichiers
file:
  upload-dir: uploads

# Configuration pour la taille maximale des fichiers


# Configuration de Port et context path de API
server:
  port: 8080
  servlet:
    context-path: /api/collab-dev/v1


