spring:
  application:
    name: api-collab-dev
  # base de donnee configuration
  datasource:
    url: jdbc:mysql://localhost:3306/collabdevDB
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect




# Configuration de Port et context path de API
server:
  port: 8080
  servlet:
    context-path: /api/collab-dev/v1


#Configuration du server SMTP
  spring:
    mail:
      host: smtp.example.com
      port: 587
      username: hamzasanmo@gmail.com
      password: joqn jmbw itsg gkde
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true



