# Configuration principale Spring
spring:
  application:
    name: api-collab-dev

  # Configuration de la base de données
  datasource:
    url: jdbc:mysql://localhost:3306/collabdevDB
    username: root
    password: rootUser
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configuration de JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Configuration du serveur SMTP (envoi d'e-mails)
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password: joqn jmbw itsg gkde
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Configuration du serveur (port et context path)
server:
  port: 8080
  servlet:
    context-path: /api/collab-dev/v1
    # Configuration du chemin pour le stockage des fichiers dans le bureau :) douking ^_~ 😎😎
file:
  upload-dir: /Users/MacBookAir/desktop


logging:
  level:
    com.team3.api_collab_dev : DEBUG
    org.springframework.web : DEBUG
