package com.team3.api_collab_dev.enumType;
/**
public enum Domain {
    IA,
    MACHINE_LEARNING,
    DATA_SCIENCE,
    BLOCKCHAIN,
    IOT,
    CYBERSECURITE,
    CLOUD_COMPUTING,
    REALITE_AUGMENTEE,
    REALITE_VIRTUELLE,
    REALITE_MIXTE,
    EDGE_COMPUTING,
    INFORMATIQUE_QUANTIQUE,
    ROBOTIQUE,
    IMPRESSION_3D,
    TECHNOLOGIES_SPATIALES,
    BIOTECHNOLOGIE,
    GREENTECH,
    FINTECH,
    SANTE_NUMERIQUE,
    AGRITECH

}*/

public enum Domain {
    INTELLIGENCE_ARTIFICIELLE,
    APPRENTISSAGE_AUTOMATIQUE,
    SCIENCE_DES_DONNEES,
    BLOCKCHAIN,
    INTERNET_DES_OBJETS,
    CYBERSECURITE,
    INFORMATIQUE_EN_NUAGE,
    REALITE_AUGMENTEE,
    REALITE_VIRTUELLE,
    REALITE_MIXTE,
    INFORMATIQUE_EN_PERIPHERIE,
    INFORMATIQUE_QUANTIQUE,
    ROBOTIQUE,
    IMPRESSION_3D,
    TECHNOLOGIE_SPATIALE,
    BIOTECHNOLOGIE,
    TECHNOLOGIE_VERTE,
    FINTECH,
    SANTE_NUMERIQUE,
    AGRITECH

}
